using System;

namespace JetBrains.ReSharper.PowerToys.CyclomaticComplexity
{
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCode()]
  [global::System.Runtime.CompilerServices.CompilerGenerated()]
  internal class Stringtable {
        
    private static global::System.Resources.ResourceManager resourceMan;
        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Stringtable() {
    }
        
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetBrains.ReSharper.PowerToys.CyclomaticComplexity.Stringtable", typeof(Stringtable).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }
        
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }
        
    /// <summary>
    ///   Looks up a localized string similar to This page allows configuring cyclomatic complexity analyzer. The analyzer calculates cyclomatic complexity for methods in the current file. For methods with complexity exceeding threshold specified below it displays the high complexity warning..
    /// </summary>
    internal static string Options_Banner {
      get {
        return ResourceManager.GetString("Options_Banner", resourceCulture);
      }
    }
        
    /// <summary>
    ///   Looks up a localized string similar to Cyclomatic complexity threshold:.
    /// </summary>
    internal static string Options_ThresholdLabel {
      get {
        return ResourceManager.GetString("Options_ThresholdLabel", resourceCulture);
      }
    }
  }
}