//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by TokenGenerator
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using JetBrains.ReSharper.Psi;
using JetBrains.ReSharper.Psi.ExtensionsAPI.Tree;
using JetBrains.Text;
using JetBrains.ReSharper.Psi.Parsing;

namespace JetBrains.ReSharper.PsiPlugin.Psi.Psi.Parsing
{
  public static partial class PsiTokenType
  {
    #region ABSTRACT
    private class AbstractNodeType : KeywordTokenNodeType
    {
      public AbstractNodeType(): base ("ABSTRACT", "abstract") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new AbstractTokenElement(this);
      }
    }
    private class AbstractTokenElement : FixedTokenElement
    {
      public AbstractTokenElement(AbstractNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ABSTRACT = new AbstractNodeType();
    #endregion
    #region ERRORHANDLING
    private class ErrorhandlingNodeType : KeywordTokenNodeType
    {
      public ErrorhandlingNodeType(): base ("ERRORHANDLING", "errorhandling") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new ErrorhandlingTokenElement(this);
      }
    }
    private class ErrorhandlingTokenElement : FixedTokenElement
    {
      public ErrorhandlingTokenElement(ErrorhandlingNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ERRORHANDLING = new ErrorhandlingNodeType();
    #endregion
    #region EXTRAS
    private class ExtrasNodeType : KeywordTokenNodeType
    {
      public ExtrasNodeType(): base ("EXTRAS", "extras") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new ExtrasTokenElement(this);
      }
    }
    private class ExtrasTokenElement : FixedTokenElement
    {
      public ExtrasTokenElement(ExtrasNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType EXTRAS = new ExtrasNodeType();
    #endregion
    #region GET
    private class GetNodeType : KeywordTokenNodeType
    {
      public GetNodeType(): base ("GET", "get") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new GetTokenElement(this);
      }
    }
    private class GetTokenElement : FixedTokenElement
    {
      public GetTokenElement(GetNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType GET = new GetNodeType();
    #endregion
    #region GETTER
    private class GetterNodeType : KeywordTokenNodeType
    {
      public GetterNodeType(): base ("GETTER", "getter") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new GetterTokenElement(this);
      }
    }
    private class GetterTokenElement : FixedTokenElement
    {
      public GetterTokenElement(GetterNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType GETTER = new GetterNodeType();
    #endregion
    #region OPTIONS
    private class OptionsNodeType : KeywordTokenNodeType
    {
      public OptionsNodeType(): base ("OPTIONS", "options") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new OptionsTokenElement(this);
      }
    }
    private class OptionsTokenElement : FixedTokenElement
    {
      public OptionsTokenElement(OptionsNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType OPTIONS = new OptionsNodeType();
    #endregion
    #region INTERFACE
    private class InterfaceNodeType : KeywordTokenNodeType
    {
      public InterfaceNodeType(): base ("INTERFACE", "interface") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new InterfaceTokenElement(this);
      }
    }
    private class InterfaceTokenElement : FixedTokenElement
    {
      public InterfaceTokenElement(InterfaceNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType INTERFACE = new InterfaceNodeType();
    #endregion
    #region INTERFACES
    private class InterfacesNodeType : KeywordTokenNodeType
    {
      public InterfacesNodeType(): base ("INTERFACES", "interfaces") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new InterfacesTokenElement(this);
      }
    }
    private class InterfacesTokenElement : FixedTokenElement
    {
      public InterfacesTokenElement(InterfacesNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType INTERFACES = new InterfacesNodeType();
    #endregion
    #region ISCACHED
    private class IscachedNodeType : KeywordTokenNodeType
    {
      public IscachedNodeType(): base ("ISCACHED", "isCached") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new IscachedTokenElement(this);
      }
    }
    private class IscachedTokenElement : FixedTokenElement
    {
      public IscachedTokenElement(IscachedNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ISCACHED = new IscachedNodeType();
    #endregion
    #region PRIVATE
    private class PrivateNodeType : KeywordTokenNodeType
    {
      public PrivateNodeType(): base ("PRIVATE", "private") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new PrivateTokenElement(this);
      }
    }
    private class PrivateTokenElement : FixedTokenElement
    {
      public PrivateTokenElement(PrivateNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType PRIVATE = new PrivateNodeType();
    #endregion
    #region PATHS
    private class PathsNodeType : KeywordTokenNodeType
    {
      public PathsNodeType(): base ("PATHS", "paths") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new PathsTokenElement(this);
      }
    }
    private class PathsTokenElement : FixedTokenElement
    {
      public PathsTokenElement(PathsNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType PATHS = new PathsNodeType();
    #endregion
    #region RETURN_TYPE
    private class ReturnTypeNodeType : KeywordTokenNodeType
    {
      public ReturnTypeNodeType(): base ("RETURN_TYPE", "returnType") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new ReturnTypeTokenElement(this);
      }
    }
    private class ReturnTypeTokenElement : FixedTokenElement
    {
      public ReturnTypeTokenElement(ReturnTypeNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType RETURN_TYPE = new ReturnTypeNodeType();
    #endregion
    #region ROLE_KEYWORD
    private class RoleKeywordNodeType : KeywordTokenNodeType
    {
      public RoleKeywordNodeType(): base ("ROLE_KEYWORD", "ROLE") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new RoleKeywordTokenElement(this);
      }
    }
    private class RoleKeywordTokenElement : FixedTokenElement
    {
      public RoleKeywordTokenElement(RoleKeywordNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ROLE_KEYWORD = new RoleKeywordNodeType();
    #endregion
    #region ROLE_KEYWORD_LOWER
    private class RoleKeywordLowerNodeType : KeywordTokenNodeType
    {
      public RoleKeywordLowerNodeType(): base ("ROLE_KEYWORD_LOWER", "Role") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new RoleKeywordLowerTokenElement(this);
      }
    }
    private class RoleKeywordLowerTokenElement : FixedTokenElement
    {
      public RoleKeywordLowerTokenElement(RoleKeywordLowerNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ROLE_KEYWORD_LOWER = new RoleKeywordLowerNodeType();
    #endregion
    #region CACHED
    private class CachedNodeType : KeywordTokenNodeType
    {
      public CachedNodeType(): base ("CACHED", "cached") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new CachedTokenElement(this);
      }
    }
    private class CachedTokenElement : FixedTokenElement
    {
      public CachedTokenElement(CachedNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType CACHED = new CachedNodeType();
    #endregion
    #region NULL_KEYWORD
    private class NullKeywordNodeType : KeywordTokenNodeType
    {
      public NullKeywordNodeType(): base ("NULL_KEYWORD", "null") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new NullKeywordTokenElement(this);
      }
    }
    private class NullKeywordTokenElement : FixedTokenElement
    {
      public NullKeywordTokenElement(NullKeywordNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType NULL_KEYWORD = new NullKeywordNodeType();
    #endregion
    #region LIST_KEYWORD
    private class ListKeywordNodeType : KeywordTokenNodeType
    {
      public ListKeywordNodeType(): base ("LIST_KEYWORD", "LIST") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new ListKeywordTokenElement(this);
      }
    }
    private class ListKeywordTokenElement : FixedTokenElement
    {
      public ListKeywordTokenElement(ListKeywordNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LIST_KEYWORD = new ListKeywordNodeType();
    #endregion
    #region SEP_KEYWORD
    private class SepKeywordNodeType : KeywordTokenNodeType
    {
      public SepKeywordNodeType(): base ("SEP_KEYWORD", "SEP") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new SepKeywordTokenElement(this);
      }
    }
    private class SepKeywordTokenElement : FixedTokenElement
    {
      public SepKeywordTokenElement(SepKeywordNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType SEP_KEYWORD = new SepKeywordNodeType();
    #endregion

    #region LPARENTH
    private class LparenthNodeType : FixedTokenNodeType
    {
      public LparenthNodeType(): base ("LPARENTH", "(") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new LparenthTokenElement(this);
      }
    }
    private class LparenthTokenElement : FixedTokenElement
    {
      public LparenthTokenElement(LparenthNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LPARENTH = new LparenthNodeType();
    #endregion
    #region RPARENTH
    private class RparenthNodeType : FixedTokenNodeType
    {
      public RparenthNodeType(): base ("RPARENTH", ")") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new RparenthTokenElement(this);
      }
    }
    private class RparenthTokenElement : FixedTokenElement
    {
      public RparenthTokenElement(RparenthNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType RPARENTH = new RparenthNodeType();
    #endregion
    #region LBRACE
    private class LbraceNodeType : FixedTokenNodeType
    {
      public LbraceNodeType(): base ("LBRACE", "{") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new LbraceTokenElement(this);
      }
    }
    private class LbraceTokenElement : FixedTokenElement
    {
      public LbraceTokenElement(LbraceNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LBRACE = new LbraceNodeType();
    #endregion
    #region RBRACE
    private class RbraceNodeType : FixedTokenNodeType
    {
      public RbraceNodeType(): base ("RBRACE", "}") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new RbraceTokenElement(this);
      }
    }
    private class RbraceTokenElement : FixedTokenElement
    {
      public RbraceTokenElement(RbraceNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType RBRACE = new RbraceNodeType();
    #endregion
    #region LBRACKET
    private class LbracketNodeType : FixedTokenNodeType
    {
      public LbracketNodeType(): base ("LBRACKET", "[") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new LbracketTokenElement(this);
      }
    }
    private class LbracketTokenElement : FixedTokenElement
    {
      public LbracketTokenElement(LbracketNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LBRACKET = new LbracketNodeType();
    #endregion
    #region RBRACKET
    private class RbracketNodeType : FixedTokenNodeType
    {
      public RbracketNodeType(): base ("RBRACKET", "]") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new RbracketTokenElement(this);
      }
    }
    private class RbracketTokenElement : FixedTokenElement
    {
      public RbracketTokenElement(RbracketNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType RBRACKET = new RbracketNodeType();
    #endregion
    #region SEMICOLON
    private class SemicolonNodeType : FixedTokenNodeType
    {
      public SemicolonNodeType(): base ("SEMICOLON", ";") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new SemicolonTokenElement(this);
      }
    }
    private class SemicolonTokenElement : FixedTokenElement
    {
      public SemicolonTokenElement(SemicolonNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType SEMICOLON = new SemicolonNodeType();
    #endregion
    #region COMMA
    private class CommaNodeType : FixedTokenNodeType
    {
      public CommaNodeType(): base ("COMMA", ",") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new CommaTokenElement(this);
      }
    }
    private class CommaTokenElement : FixedTokenElement
    {
      public CommaTokenElement(CommaNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType COMMA = new CommaNodeType();
    #endregion
    #region DOT
    private class DotNodeType : FixedTokenNodeType
    {
      public DotNodeType(): base ("DOT", ".") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new DotTokenElement(this);
      }
    }
    private class DotTokenElement : FixedTokenElement
    {
      public DotTokenElement(DotNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType DOT = new DotNodeType();
    #endregion
    #region EQ
    private class EqNodeType : FixedTokenNodeType
    {
      public EqNodeType(): base ("EQ", "=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new EqTokenElement(this);
      }
    }
    private class EqTokenElement : FixedTokenElement
    {
      public EqTokenElement(EqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType EQ = new EqNodeType();
    #endregion
    #region GT
    private class GtNodeType : FixedTokenNodeType
    {
      public GtNodeType(): base ("GT", ">") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new GtTokenElement(this);
      }
    }
    private class GtTokenElement : FixedTokenElement
    {
      public GtTokenElement(GtNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType GT = new GtNodeType();
    #endregion
    #region LT
    private class LtNodeType : FixedTokenNodeType
    {
      public LtNodeType(): base ("LT", "<") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new LtTokenElement(this);
      }
    }
    private class LtTokenElement : FixedTokenElement
    {
      public LtTokenElement(LtNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LT = new LtNodeType();
    #endregion
    #region EXCL
    private class ExclNodeType : FixedTokenNodeType
    {
      public ExclNodeType(): base ("EXCL", "!") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new ExclTokenElement(this);
      }
    }
    private class ExclTokenElement : FixedTokenElement
    {
      public ExclTokenElement(ExclNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType EXCL = new ExclNodeType();
    #endregion
    #region TILDE
    private class TildeNodeType : FixedTokenNodeType
    {
      public TildeNodeType(): base ("TILDE", "~") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new TildeTokenElement(this);
      }
    }
    private class TildeTokenElement : FixedTokenElement
    {
      public TildeTokenElement(TildeNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType TILDE = new TildeNodeType();
    #endregion
    #region SHARP
    private class SharpNodeType : FixedTokenNodeType
    {
      public SharpNodeType(): base ("SHARP", "#") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new SharpTokenElement(this);
      }
    }
    private class SharpTokenElement : FixedTokenElement
    {
      public SharpTokenElement(SharpNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType SHARP = new SharpNodeType();
    #endregion
    #region AT
    private class AtNodeType : FixedTokenNodeType
    {
      public AtNodeType(): base ("AT", "@") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new AtTokenElement(this);
      }
    }
    private class AtTokenElement : FixedTokenElement
    {
      public AtTokenElement(AtNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType AT = new AtNodeType();
    #endregion
    #region BACK_QUOTE
    private class BackQuoteNodeType : FixedTokenNodeType
    {
      public BackQuoteNodeType(): base ("BACK_QUOTE", "`") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new BackQuoteTokenElement(this);
      }
    }
    private class BackQuoteTokenElement : FixedTokenElement
    {
      public BackQuoteTokenElement(BackQuoteNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType BACK_QUOTE = new BackQuoteNodeType();
    #endregion
    #region QUOTE
    private class QuoteNodeType : FixedTokenNodeType
    {
      public QuoteNodeType(): base ("QUOTE", "'") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new QuoteTokenElement(this);
      }
    }
    private class QuoteTokenElement : FixedTokenElement
    {
      public QuoteTokenElement(QuoteNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType QUOTE = new QuoteNodeType();
    #endregion
    #region DOUBLE_QUOT
    private class DoubleQuotNodeType : FixedTokenNodeType
    {
      public DoubleQuotNodeType(): base ("DOUBLE_QUOT", "\"") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new DoubleQuotTokenElement(this);
      }
    }
    private class DoubleQuotTokenElement : FixedTokenElement
    {
      public DoubleQuotTokenElement(DoubleQuotNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType DOUBLE_QUOT = new DoubleQuotNodeType();
    #endregion
    #region QUEST
    private class QuestNodeType : FixedTokenNodeType
    {
      public QuestNodeType(): base ("QUEST", "?") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new QuestTokenElement(this);
      }
    }
    private class QuestTokenElement : FixedTokenElement
    {
      public QuestTokenElement(QuestNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType QUEST = new QuestNodeType();
    #endregion
    #region COLON
    private class ColonNodeType : FixedTokenNodeType
    {
      public ColonNodeType(): base ("COLON", ":") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new ColonTokenElement(this);
      }
    }
    private class ColonTokenElement : FixedTokenElement
    {
      public ColonTokenElement(ColonNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType COLON = new ColonNodeType();
    #endregion
    #region PLUS
    private class PlusNodeType : FixedTokenNodeType
    {
      public PlusNodeType(): base ("PLUS", "+") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new PlusTokenElement(this);
      }
    }
    private class PlusTokenElement : FixedTokenElement
    {
      public PlusTokenElement(PlusNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType PLUS = new PlusNodeType();
    #endregion
    #region MINUS
    private class MinusNodeType : FixedTokenNodeType
    {
      public MinusNodeType(): base ("MINUS", "-") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new MinusTokenElement(this);
      }
    }
    private class MinusTokenElement : FixedTokenElement
    {
      public MinusTokenElement(MinusNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType MINUS = new MinusNodeType();
    #endregion
    #region ASTERISK
    private class AsteriskNodeType : FixedTokenNodeType
    {
      public AsteriskNodeType(): base ("ASTERISK", "*") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new AsteriskTokenElement(this);
      }
    }
    private class AsteriskTokenElement : FixedTokenElement
    {
      public AsteriskTokenElement(AsteriskNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ASTERISK = new AsteriskNodeType();
    #endregion
    #region DIV
    private class DivNodeType : FixedTokenNodeType
    {
      public DivNodeType(): base ("DIV", "/") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new DivTokenElement(this);
      }
    }
    private class DivTokenElement : FixedTokenElement
    {
      public DivTokenElement(DivNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType DIV = new DivNodeType();
    #endregion
    #region BACK_SLASH
    private class BackSlashNodeType : FixedTokenNodeType
    {
      public BackSlashNodeType(): base ("BACK_SLASH", "\\") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new BackSlashTokenElement(this);
      }
    }
    private class BackSlashTokenElement : FixedTokenElement
    {
      public BackSlashTokenElement(BackSlashNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType BACK_SLASH = new BackSlashNodeType();
    #endregion
    #region AND
    private class AndNodeType : FixedTokenNodeType
    {
      public AndNodeType(): base ("AND", "&") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new AndTokenElement(this);
      }
    }
    private class AndTokenElement : FixedTokenElement
    {
      public AndTokenElement(AndNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType AND = new AndNodeType();
    #endregion
    #region OR
    private class OrNodeType : FixedTokenNodeType
    {
      public OrNodeType(): base ("OR", "|") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new OrTokenElement(this);
      }
    }
    private class OrTokenElement : FixedTokenElement
    {
      public OrTokenElement(OrNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType OR = new OrNodeType();
    #endregion
    #region XOR
    private class XorNodeType : FixedTokenNodeType
    {
      public XorNodeType(): base ("XOR", "^") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new XorTokenElement(this);
      }
    }
    private class XorTokenElement : FixedTokenElement
    {
      public XorTokenElement(XorNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType XOR = new XorNodeType();
    #endregion
    #region PERC
    private class PercNodeType : FixedTokenNodeType
    {
      public PercNodeType(): base ("PERC", "%") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new PercTokenElement(this);
      }
    }
    private class PercTokenElement : FixedTokenElement
    {
      public PercTokenElement(PercNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType PERC = new PercNodeType();
    #endregion
    #region DOLLAR
    private class DollarNodeType : FixedTokenNodeType
    {
      public DollarNodeType(): base ("DOLLAR", "$") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new DollarTokenElement(this);
      }
    }
    private class DollarTokenElement : FixedTokenElement
    {
      public DollarTokenElement(DollarNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType DOLLAR = new DollarNodeType();
    #endregion
    #region EQEQ
    private class EqeqNodeType : FixedTokenNodeType
    {
      public EqeqNodeType(): base ("EQEQ", "==") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new EqeqTokenElement(this);
      }
    }
    private class EqeqTokenElement : FixedTokenElement
    {
      public EqeqTokenElement(EqeqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType EQEQ = new EqeqNodeType();
    #endregion
    #region LE
    private class LeNodeType : FixedTokenNodeType
    {
      public LeNodeType(): base ("LE", "<=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new LeTokenElement(this);
      }
    }
    private class LeTokenElement : FixedTokenElement
    {
      public LeTokenElement(LeNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LE = new LeNodeType();
    #endregion
    #region GE
    private class GeNodeType : FixedTokenNodeType
    {
      public GeNodeType(): base ("GE", ">=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new GeTokenElement(this);
      }
    }
    private class GeTokenElement : FixedTokenElement
    {
      public GeTokenElement(GeNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType GE = new GeNodeType();
    #endregion
    #region NE
    private class NeNodeType : FixedTokenNodeType
    {
      public NeNodeType(): base ("NE", "!=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new NeTokenElement(this);
      }
    }
    private class NeTokenElement : FixedTokenElement
    {
      public NeTokenElement(NeNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType NE = new NeNodeType();
    #endregion
    #region ANDAND
    private class AndandNodeType : FixedTokenNodeType
    {
      public AndandNodeType(): base ("ANDAND", "&&") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new AndandTokenElement(this);
      }
    }
    private class AndandTokenElement : FixedTokenElement
    {
      public AndandTokenElement(AndandNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ANDAND = new AndandNodeType();
    #endregion
    #region OROR
    private class OrorNodeType : FixedTokenNodeType
    {
      public OrorNodeType(): base ("OROR", "||") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new OrorTokenElement(this);
      }
    }
    private class OrorTokenElement : FixedTokenElement
    {
      public OrorTokenElement(OrorNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType OROR = new OrorNodeType();
    #endregion
    #region PLUSPLUS
    private class PlusplusNodeType : FixedTokenNodeType
    {
      public PlusplusNodeType(): base ("PLUSPLUS", "++") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new PlusplusTokenElement(this);
      }
    }
    private class PlusplusTokenElement : FixedTokenElement
    {
      public PlusplusTokenElement(PlusplusNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType PLUSPLUS = new PlusplusNodeType();
    #endregion
    #region MINUSMINUS
    private class MinusminusNodeType : FixedTokenNodeType
    {
      public MinusminusNodeType(): base ("MINUSMINUS", "--") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new MinusminusTokenElement(this);
      }
    }
    private class MinusminusTokenElement : FixedTokenElement
    {
      public MinusminusTokenElement(MinusminusNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType MINUSMINUS = new MinusminusNodeType();
    #endregion
    #region LTLT
    private class LtltNodeType : FixedTokenNodeType
    {
      public LtltNodeType(): base ("LTLT", "<<") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new LtltTokenElement(this);
      }
    }
    private class LtltTokenElement : FixedTokenElement
    {
      public LtltTokenElement(LtltNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LTLT = new LtltNodeType();
    #endregion
    #region GTGT
    private class GtgtNodeType : FixedTokenNodeType
    {
      public GtgtNodeType(): base ("GTGT", ">>") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new GtgtTokenElement(this);
      }
    }
    private class GtgtTokenElement : FixedTokenElement
    {
      public GtgtTokenElement(GtgtNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType GTGT = new GtgtNodeType();
    #endregion
    #region PLUSEQ
    private class PluseqNodeType : FixedTokenNodeType
    {
      public PluseqNodeType(): base ("PLUSEQ", "+=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new PluseqTokenElement(this);
      }
    }
    private class PluseqTokenElement : FixedTokenElement
    {
      public PluseqTokenElement(PluseqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType PLUSEQ = new PluseqNodeType();
    #endregion
    #region MINUSEQ
    private class MinuseqNodeType : FixedTokenNodeType
    {
      public MinuseqNodeType(): base ("MINUSEQ", "-=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new MinuseqTokenElement(this);
      }
    }
    private class MinuseqTokenElement : FixedTokenElement
    {
      public MinuseqTokenElement(MinuseqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType MINUSEQ = new MinuseqNodeType();
    #endregion
    #region ASTERISKEQ
    private class AsteriskeqNodeType : FixedTokenNodeType
    {
      public AsteriskeqNodeType(): base ("ASTERISKEQ", "*=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new AsteriskeqTokenElement(this);
      }
    }
    private class AsteriskeqTokenElement : FixedTokenElement
    {
      public AsteriskeqTokenElement(AsteriskeqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ASTERISKEQ = new AsteriskeqNodeType();
    #endregion
    #region DIVEQ
    private class DiveqNodeType : FixedTokenNodeType
    {
      public DiveqNodeType(): base ("DIVEQ", "/=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new DiveqTokenElement(this);
      }
    }
    private class DiveqTokenElement : FixedTokenElement
    {
      public DiveqTokenElement(DiveqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType DIVEQ = new DiveqNodeType();
    #endregion
    #region ANDEQ
    private class AndeqNodeType : FixedTokenNodeType
    {
      public AndeqNodeType(): base ("ANDEQ", "&=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new AndeqTokenElement(this);
      }
    }
    private class AndeqTokenElement : FixedTokenElement
    {
      public AndeqTokenElement(AndeqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ANDEQ = new AndeqNodeType();
    #endregion
    #region OREQ
    private class OreqNodeType : FixedTokenNodeType
    {
      public OreqNodeType(): base ("OREQ", "|=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new OreqTokenElement(this);
      }
    }
    private class OreqTokenElement : FixedTokenElement
    {
      public OreqTokenElement(OreqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType OREQ = new OreqNodeType();
    #endregion
    #region XOREQ
    private class XoreqNodeType : FixedTokenNodeType
    {
      public XoreqNodeType(): base ("XOREQ", "^=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new XoreqTokenElement(this);
      }
    }
    private class XoreqTokenElement : FixedTokenElement
    {
      public XoreqTokenElement(XoreqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType XOREQ = new XoreqNodeType();
    #endregion
    #region PERCEQ
    private class PerceqNodeType : FixedTokenNodeType
    {
      public PerceqNodeType(): base ("PERCEQ", "%=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new PerceqTokenElement(this);
      }
    }
    private class PerceqTokenElement : FixedTokenElement
    {
      public PerceqTokenElement(PerceqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType PERCEQ = new PerceqNodeType();
    #endregion
    #region LTLTEQ
    private class LtlteqNodeType : FixedTokenNodeType
    {
      public LtlteqNodeType(): base ("LTLTEQ", "<<=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new LtlteqTokenElement(this);
      }
    }
    private class LtlteqTokenElement : FixedTokenElement
    {
      public LtlteqTokenElement(LtlteqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LTLTEQ = new LtlteqNodeType();
    #endregion
    #region GTGTEQ
    private class GtgteqNodeType : FixedTokenNodeType
    {
      public GtgteqNodeType(): base ("GTGTEQ", ">>=") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new GtgteqTokenElement(this);
      }
    }
    private class GtgteqTokenElement : FixedTokenElement
    {
      public GtgteqTokenElement(GtgteqNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType GTGTEQ = new GtgteqNodeType();
    #endregion
    #region LAMBDA_ARROW
    private class LambdaArrowNodeType : FixedTokenNodeType
    {
      public LambdaArrowNodeType(): base ("LAMBDA_ARROW", "=>") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new LambdaArrowTokenElement(this);
      }
    }
    private class LambdaArrowTokenElement : FixedTokenElement
    {
      public LambdaArrowTokenElement(LambdaArrowNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType LAMBDA_ARROW = new LambdaArrowNodeType();
    #endregion
    #region DOUBLE_COLON
    private class DoubleColonNodeType : FixedTokenNodeType
    {
      public DoubleColonNodeType(): base ("DOUBLE_COLON", "::") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new DoubleColonTokenElement(this);
      }
    }
    private class DoubleColonTokenElement : FixedTokenElement
    {
      public DoubleColonTokenElement(DoubleColonNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType DOUBLE_COLON = new DoubleColonNodeType();
    #endregion
    #region DOUBLE_QUEST
    private class DoubleQuestNodeType : FixedTokenNodeType
    {
      public DoubleQuestNodeType(): base ("DOUBLE_QUEST", "??") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new DoubleQuestTokenElement(this);
      }
    }
    private class DoubleQuestTokenElement : FixedTokenElement
    {
      public DoubleQuestTokenElement(DoubleQuestNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType DOUBLE_QUEST = new DoubleQuestNodeType();
    #endregion
    #region ARROW
    private class ArrowNodeType : FixedTokenNodeType
    {
      public ArrowNodeType(): base ("ARROW", "->") {}
      public override LeafElementBase Create(IBuffer buffer, TreeOffset startOffset, TreeOffset endOffset)
      {
        return new ArrowTokenElement(this);
      }
    }
    private class ArrowTokenElement : FixedTokenElement
    {
      public ArrowTokenElement(ArrowNodeType tokenNodeType) : base(tokenNodeType) { }
    }
    public static readonly TokenNodeType ARROW = new ArrowNodeType();
    #endregion

  }
}
